/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThecakeisalieRouteImport } from './routes/thecakeisalie'
import { Route as ToolsRouteRouteImport } from './routes/tools/route'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as DeveloperRouteRouteImport } from './routes/developer/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as DeveloperIndexRouteImport } from './routes/developer/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ToolsUnderConstructionRouteImport } from './routes/tools/under-construction'
import { Route as ToolsLegacyRouteImport } from './routes/tools/legacy'
import { Route as ToolsBogeyRouteImport } from './routes/tools/bogey'
import { Route as ToolsBirdieRouteImport } from './routes/tools/birdie'
import { Route as ProgramsProgramRouteImport } from './routes/programs/$program'
import { Route as PostsAtChar123authorChar125RouteImport } from './routes/posts/@{$author}'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as GoSlugRouteImport } from './routes/go.$slug'
import { Route as EdaReportRouteImport } from './routes/eda/report'
import { Route as DeveloperSignatureRouteImport } from './routes/developer/signature'
import { Route as DeveloperErrRouteImport } from './routes/developer/err'
import { Route as Developer404RouteImport } from './routes/developer/404'
import { Route as AliasesTeamRouteImport } from './routes/_aliases/team'
import { Route as AliasesContactRouteImport } from './routes/_aliases/contact'
import { Route as AliasesAboutUsRouteImport } from './routes/_aliases/about-us'
import { Route as DeveloperNestedRouteRouteImport } from './routes/developer/nested/route'
import { Route as PostsTagTagRouteImport } from './routes/posts/tag.$tag'
import { Route as DeveloperNestedTest1Test2RouteImport } from './routes/developer/nested/test1.test2'

const ThecakeisalieRoute = ThecakeisalieRouteImport.update({
  id: '/thecakeisalie',
  path: '/thecakeisalie',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRouteRoute = DeveloperRouteRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeveloperRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUnderConstructionRoute = ToolsUnderConstructionRouteImport.update({
  id: '/under-construction',
  path: '/under-construction',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsLegacyRoute = ToolsLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsBogeyRoute = ToolsBogeyRouteImport.update({
  id: '/bogey',
  path: '/bogey',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsBirdieRoute = ToolsBirdieRouteImport.update({
  id: '/birdie',
  path: '/birdie',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ProgramsProgramRoute = ProgramsProgramRouteImport.update({
  id: '/programs/$program',
  path: '/programs/$program',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsAtChar123authorChar125Route =
  PostsAtChar123authorChar125RouteImport.update({
    id: '/@{$author}',
    path: '/@{$author}',
    getParentRoute: () => PostsRouteRoute,
  } as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EdaReportRoute = EdaReportRouteImport.update({
  id: '/eda/report',
  path: '/eda/report',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSignatureRoute = DeveloperSignatureRouteImport.update({
  id: '/signature',
  path: '/signature',
  getParentRoute: () => DeveloperRouteRoute,
} as any)
const DeveloperErrRoute = DeveloperErrRouteImport.update({
  id: '/err',
  path: '/err',
  getParentRoute: () => DeveloperRouteRoute,
} as any)
const Developer404Route = Developer404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => DeveloperRouteRoute,
} as any)
const AliasesTeamRoute = AliasesTeamRouteImport.update({
  id: '/_aliases/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasesContactRoute = AliasesContactRouteImport.update({
  id: '/_aliases/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasesAboutUsRoute = AliasesAboutUsRouteImport.update({
  id: '/_aliases/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperNestedRouteRoute = DeveloperNestedRouteRouteImport.update({
  id: '/nested',
  path: '/nested',
  getParentRoute: () => DeveloperRouteRoute,
} as any)
const PostsTagTagRoute = PostsTagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => PostsRouteRoute,
} as any)
const DeveloperNestedTest1Test2Route =
  DeveloperNestedTest1Test2RouteImport.update({
    id: '/test1/test2',
    path: '/test1/test2',
    getParentRoute: () => DeveloperNestedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developer': typeof DeveloperRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/tools': typeof ToolsRouteRouteWithChildren
  '/thecakeisalie': typeof ThecakeisalieRoute
  '/developer/nested': typeof DeveloperNestedRouteRouteWithChildren
  '/about-us': typeof AliasesAboutUsRoute
  '/contact': typeof AliasesContactRoute
  '/team': typeof AliasesTeamRoute
  '/developer/404': typeof Developer404Route
  '/developer/err': typeof DeveloperErrRoute
  '/developer/signature': typeof DeveloperSignatureRoute
  '/eda/report': typeof EdaReportRoute
  '/go/$slug': typeof GoSlugRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/@{$author}': typeof PostsAtChar123authorChar125Route
  '/programs/$program': typeof ProgramsProgramRoute
  '/tools/birdie': typeof ToolsBirdieRoute
  '/tools/bogey': typeof ToolsBogeyRoute
  '/tools/legacy': typeof ToolsLegacyRoute
  '/tools/under-construction': typeof ToolsUnderConstructionRoute
  '/about/': typeof AboutIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/posts/tag/$tag': typeof PostsTagTagRoute
  '/developer/nested/test1/test2': typeof DeveloperNestedTest1Test2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thecakeisalie': typeof ThecakeisalieRoute
  '/developer/nested': typeof DeveloperNestedRouteRouteWithChildren
  '/about-us': typeof AliasesAboutUsRoute
  '/contact': typeof AliasesContactRoute
  '/team': typeof AliasesTeamRoute
  '/developer/404': typeof Developer404Route
  '/developer/err': typeof DeveloperErrRoute
  '/developer/signature': typeof DeveloperSignatureRoute
  '/eda/report': typeof EdaReportRoute
  '/go/$slug': typeof GoSlugRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/@{$author}': typeof PostsAtChar123authorChar125Route
  '/programs/$program': typeof ProgramsProgramRoute
  '/tools/birdie': typeof ToolsBirdieRoute
  '/tools/bogey': typeof ToolsBogeyRoute
  '/tools/legacy': typeof ToolsLegacyRoute
  '/tools/under-construction': typeof ToolsUnderConstructionRoute
  '/about': typeof AboutIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/posts': typeof PostsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/posts/tag/$tag': typeof PostsTagTagRoute
  '/developer/nested/test1/test2': typeof DeveloperNestedTest1Test2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/developer': typeof DeveloperRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/tools': typeof ToolsRouteRouteWithChildren
  '/thecakeisalie': typeof ThecakeisalieRoute
  '/developer/nested': typeof DeveloperNestedRouteRouteWithChildren
  '/_aliases/about-us': typeof AliasesAboutUsRoute
  '/_aliases/contact': typeof AliasesContactRoute
  '/_aliases/team': typeof AliasesTeamRoute
  '/developer/404': typeof Developer404Route
  '/developer/err': typeof DeveloperErrRoute
  '/developer/signature': typeof DeveloperSignatureRoute
  '/eda/report': typeof EdaReportRoute
  '/go/$slug': typeof GoSlugRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/@{$author}': typeof PostsAtChar123authorChar125Route
  '/programs/$program': typeof ProgramsProgramRoute
  '/tools/birdie': typeof ToolsBirdieRoute
  '/tools/bogey': typeof ToolsBogeyRoute
  '/tools/legacy': typeof ToolsLegacyRoute
  '/tools/under-construction': typeof ToolsUnderConstructionRoute
  '/about/': typeof AboutIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/posts/tag/$tag': typeof PostsTagTagRoute
  '/developer/nested/test1/test2': typeof DeveloperNestedTest1Test2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developer'
    | '/posts'
    | '/tools'
    | '/thecakeisalie'
    | '/developer/nested'
    | '/about-us'
    | '/contact'
    | '/team'
    | '/developer/404'
    | '/developer/err'
    | '/developer/signature'
    | '/eda/report'
    | '/go/$slug'
    | '/posts/$postId'
    | '/posts/@{$author}'
    | '/programs/$program'
    | '/tools/birdie'
    | '/tools/bogey'
    | '/tools/legacy'
    | '/tools/under-construction'
    | '/about/'
    | '/developer/'
    | '/posts/'
    | '/tools/'
    | '/posts/tag/$tag'
    | '/developer/nested/test1/test2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/thecakeisalie'
    | '/developer/nested'
    | '/about-us'
    | '/contact'
    | '/team'
    | '/developer/404'
    | '/developer/err'
    | '/developer/signature'
    | '/eda/report'
    | '/go/$slug'
    | '/posts/$postId'
    | '/posts/@{$author}'
    | '/programs/$program'
    | '/tools/birdie'
    | '/tools/bogey'
    | '/tools/legacy'
    | '/tools/under-construction'
    | '/about'
    | '/developer'
    | '/posts'
    | '/tools'
    | '/posts/tag/$tag'
    | '/developer/nested/test1/test2'
  id:
    | '__root__'
    | '/'
    | '/developer'
    | '/posts'
    | '/tools'
    | '/thecakeisalie'
    | '/developer/nested'
    | '/_aliases/about-us'
    | '/_aliases/contact'
    | '/_aliases/team'
    | '/developer/404'
    | '/developer/err'
    | '/developer/signature'
    | '/eda/report'
    | '/go/$slug'
    | '/posts/$postId'
    | '/posts/@{$author}'
    | '/programs/$program'
    | '/tools/birdie'
    | '/tools/bogey'
    | '/tools/legacy'
    | '/tools/under-construction'
    | '/about/'
    | '/developer/'
    | '/posts/'
    | '/tools/'
    | '/posts/tag/$tag'
    | '/developer/nested/test1/test2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeveloperRouteRoute: typeof DeveloperRouteRouteWithChildren
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  ToolsRouteRoute: typeof ToolsRouteRouteWithChildren
  ThecakeisalieRoute: typeof ThecakeisalieRoute
  AliasesAboutUsRoute: typeof AliasesAboutUsRoute
  AliasesContactRoute: typeof AliasesContactRoute
  AliasesTeamRoute: typeof AliasesTeamRoute
  EdaReportRoute: typeof EdaReportRoute
  GoSlugRoute: typeof GoSlugRoute
  ProgramsProgramRoute: typeof ProgramsProgramRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thecakeisalie': {
      id: '/thecakeisalie'
      path: '/thecakeisalie'
      fullPath: '/thecakeisalie'
      preLoaderRoute: typeof ThecakeisalieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/developer/': {
      id: '/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof DeveloperRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/under-construction': {
      id: '/tools/under-construction'
      path: '/under-construction'
      fullPath: '/tools/under-construction'
      preLoaderRoute: typeof ToolsUnderConstructionRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/legacy': {
      id: '/tools/legacy'
      path: '/legacy'
      fullPath: '/tools/legacy'
      preLoaderRoute: typeof ToolsLegacyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/bogey': {
      id: '/tools/bogey'
      path: '/bogey'
      fullPath: '/tools/bogey'
      preLoaderRoute: typeof ToolsBogeyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/birdie': {
      id: '/tools/birdie'
      path: '/birdie'
      fullPath: '/tools/birdie'
      preLoaderRoute: typeof ToolsBirdieRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/programs/$program': {
      id: '/programs/$program'
      path: '/programs/$program'
      fullPath: '/programs/$program'
      preLoaderRoute: typeof ProgramsProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/@{$author}': {
      id: '/posts/@{$author}'
      path: '/@{$author}'
      fullPath: '/posts/@{$author}'
      preLoaderRoute: typeof PostsAtChar123authorChar125RouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eda/report': {
      id: '/eda/report'
      path: '/eda/report'
      fullPath: '/eda/report'
      preLoaderRoute: typeof EdaReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/signature': {
      id: '/developer/signature'
      path: '/signature'
      fullPath: '/developer/signature'
      preLoaderRoute: typeof DeveloperSignatureRouteImport
      parentRoute: typeof DeveloperRouteRoute
    }
    '/developer/err': {
      id: '/developer/err'
      path: '/err'
      fullPath: '/developer/err'
      preLoaderRoute: typeof DeveloperErrRouteImport
      parentRoute: typeof DeveloperRouteRoute
    }
    '/developer/404': {
      id: '/developer/404'
      path: '/404'
      fullPath: '/developer/404'
      preLoaderRoute: typeof Developer404RouteImport
      parentRoute: typeof DeveloperRouteRoute
    }
    '/_aliases/team': {
      id: '/_aliases/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AliasesTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_aliases/contact': {
      id: '/_aliases/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AliasesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_aliases/about-us': {
      id: '/_aliases/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AliasesAboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/nested': {
      id: '/developer/nested'
      path: '/nested'
      fullPath: '/developer/nested'
      preLoaderRoute: typeof DeveloperNestedRouteRouteImport
      parentRoute: typeof DeveloperRouteRoute
    }
    '/posts/tag/$tag': {
      id: '/posts/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/posts/tag/$tag'
      preLoaderRoute: typeof PostsTagTagRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/developer/nested/test1/test2': {
      id: '/developer/nested/test1/test2'
      path: '/test1/test2'
      fullPath: '/developer/nested/test1/test2'
      preLoaderRoute: typeof DeveloperNestedTest1Test2RouteImport
      parentRoute: typeof DeveloperNestedRouteRoute
    }
  }
}

interface DeveloperNestedRouteRouteChildren {
  DeveloperNestedTest1Test2Route: typeof DeveloperNestedTest1Test2Route
}

const DeveloperNestedRouteRouteChildren: DeveloperNestedRouteRouteChildren = {
  DeveloperNestedTest1Test2Route: DeveloperNestedTest1Test2Route,
}

const DeveloperNestedRouteRouteWithChildren =
  DeveloperNestedRouteRoute._addFileChildren(DeveloperNestedRouteRouteChildren)

interface DeveloperRouteRouteChildren {
  DeveloperNestedRouteRoute: typeof DeveloperNestedRouteRouteWithChildren
  Developer404Route: typeof Developer404Route
  DeveloperErrRoute: typeof DeveloperErrRoute
  DeveloperSignatureRoute: typeof DeveloperSignatureRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
}

const DeveloperRouteRouteChildren: DeveloperRouteRouteChildren = {
  DeveloperNestedRouteRoute: DeveloperNestedRouteRouteWithChildren,
  Developer404Route: Developer404Route,
  DeveloperErrRoute: DeveloperErrRoute,
  DeveloperSignatureRoute: DeveloperSignatureRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
}

const DeveloperRouteRouteWithChildren = DeveloperRouteRoute._addFileChildren(
  DeveloperRouteRouteChildren,
)

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsAtChar123authorChar125Route: typeof PostsAtChar123authorChar125Route
  PostsIndexRoute: typeof PostsIndexRoute
  PostsTagTagRoute: typeof PostsTagTagRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsAtChar123authorChar125Route: PostsAtChar123authorChar125Route,
  PostsIndexRoute: PostsIndexRoute,
  PostsTagTagRoute: PostsTagTagRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface ToolsRouteRouteChildren {
  ToolsBirdieRoute: typeof ToolsBirdieRoute
  ToolsBogeyRoute: typeof ToolsBogeyRoute
  ToolsLegacyRoute: typeof ToolsLegacyRoute
  ToolsUnderConstructionRoute: typeof ToolsUnderConstructionRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteRouteChildren: ToolsRouteRouteChildren = {
  ToolsBirdieRoute: ToolsBirdieRoute,
  ToolsBogeyRoute: ToolsBogeyRoute,
  ToolsLegacyRoute: ToolsLegacyRoute,
  ToolsUnderConstructionRoute: ToolsUnderConstructionRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteRouteWithChildren = ToolsRouteRoute._addFileChildren(
  ToolsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeveloperRouteRoute: DeveloperRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  ToolsRouteRoute: ToolsRouteRouteWithChildren,
  ThecakeisalieRoute: ThecakeisalieRoute,
  AliasesAboutUsRoute: AliasesAboutUsRoute,
  AliasesContactRoute: AliasesContactRoute,
  AliasesTeamRoute: AliasesTeamRoute,
  EdaReportRoute: EdaReportRoute,
  GoSlugRoute: GoSlugRoute,
  ProgramsProgramRoute: ProgramsProgramRoute,
  AboutIndexRoute: AboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
