name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true

      - name: Run vp for 3 seconds
        shell: bash
        run: |
          set -euo pipefail
          vp run &
          PID=$!
          sleep 3
          kill "$PID" || true
          wait "$PID" || true

      - name: install deps
        run: vp install

      - name: build
        run: vp run build

      - name: create 404.html
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
